require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - tmp/**/*
    - vendor/**/*
    - db/schema.rb
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Lint/SafeNavigationWithEmpty:
  Enabled: false

Metrics/AbcSize:
  Max: 35
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - db/migrate/*
    - lib/tasks/*
    - spec/**/*

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/migrate/*
    - lib/tasks/*

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - db/seeds/**/*

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - app/models/concerns/*

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": "()"
    "%I": "()"
    "%r": "()"
    "%w": "()"
    "%W": "()"
