require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/bundle
    - tmp/**/*
    - vendor/**/*
    - db/schema.rb
    - db/neo4j/schema.yml
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Lint/SafeNavigationWithEmpty:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Enabled: true
  Max: 35
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Enabled: true
  Max: 50
  Exclude:
    - db/migrate/*

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/migrate/*

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - db/seeds/**/*

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": "()"
    "%I": "()"
    "%r": "()"
    "%w": "()"
    "%W": "()"
