version: "3.7"

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: always

  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
    volumes:
      - neo4j:/data/
      - ./logs/neo4j/:/logs/
    environment:
      NEO4J_AUTH: neo4j/password
    restart: always

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - ./logs/app/:/app/log/
    depends_on:
      - neo4j
      - sidekiq
      - redis
    links:
      - neo4j
      - sidekiq
      - redis
    env_file:
      - headbanger.env
    restart: always

  web:
    build: web
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app
    restart: always

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app/
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - headbanger.env
    restart: always

volumes:
  postgres:
  redis:
  neo4j:
