version: "3.8"

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:alpine
    volumes:
      - redis:/data/

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/:cached
      - ./logs/app/:/app/log/
      - bundle:/usr/local/bundle/
    depends_on:
      - postgres
      - redis
    env_file:
      - .development.env
      - .development.env.local

  web:
    build:
      context: web
      args:
        - SENTRY_AUTH_TOKEN
    ports:
      - "80:80"
    volumes:
      - ./web/nginx/:/etc/nginx/conf.d/
      - nginx:/cache/
    depends_on:
      - app
    env_file:
      - .development.env
      - .development.env.local

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app/:cached
      - bundle:/usr/local/bundle/
    depends_on:
      - postgres
      - redis
    env_file:
      - .development.env
      - .development.env.local

  clock:
    build: .
    command: bundle exec clockwork config/clock.rb
    volumes:
      - .:/app/:cached
      - bundle:/usr/local/bundle/
    depends_on:
      - postgres
      - redis
    env_file:
      - .development.env
      - .development.env.local

  scrub:
    build: .
    command: bin/scrub
    volumes:
      - .:/app/:cached
      - bundle:/usr/local/bundle/
    depends_on:
      - postgres
      - redis
    env_file:
      - .development.env
      - .development.env.local

  musicbrainz:
    build: .
    command: bin/forward
    volumes:
      - .:/app/:cached
      - $HOME/.ssh/:/app/.ssh/:ro
      - $SSH_AUTH_SOCK:/ssh
    ports:
      - "5433:5432"
    env_file:
      - .development.env
      - .development.env.local

volumes:
  postgres:
  redis:
  nginx:
  bundle:
