version: '2'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - ./logs/app/:/app/log/
    depends_on:
      - neo4j
      - sidekiq
      - redis
    links:
      - neo4j
      - sidekiq
      - redis
    env_file:
      - headbanger.env
    restart: always

  web:
    build: web
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app
    restart: always

  neo4j:
    image: neo4j:4.0
    ports:
      - "7474:7474"
    volumes:
      - neo4j:/data/
      - ./logs/neo4j/:/logs/
    environment:
      NEO4J_AUTH: neo4j/password
    restart: always

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app/
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - headbanger.env
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: always

volumes:
  public:
  sockets:
  redis:
  neo4j:
