version: '2'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
    depends_on:
      - neo4j
      - sidekiq
      - redis
    links:
      - neo4j
      - sidekiq
      - redis
    env_file:
      - headbanger.env
    restart: always

  web:
    build: web
    ports:
      - "8080:8080"
    restart: always

  neo4j:
    image: neo4j:4.0
    ports:
      - "7474"
    volumes:
      - neo4j:/var/lib/neo4j/data
    env_file:
      - neo4j.env
    restart: always

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app/
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - headbanger.env
    restart: always

  redis:
    image: redis
    volumes:
      - redis:/data
    restart: always

volumes:
  public:
  sockets:
  redis:
  neo4j:
