version: "3.8"

x-app: &app
  build: .
  volumes:
    - .:/app/:cached
    - bundle:/usr/local/bundle/
  depends_on:
    - postgres
    - redis
  env_file: .development.env

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:alpine
    volumes:
      - redis:/data/

  app:
    <<: *app
    ports:
      - "3000:3000"

  web:
    build:
      context: web
      args:
        - SENTRY_AUTH_TOKEN
    ports:
      - "80:80"
    volumes:
      - ./web/nginx/:/etc/nginx/conf.d/
      - nginx:/cache/
    depends_on:
      - app
    env_file:
      - .development.env

  debug:
    <<: *app
    command: rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails s -b 0.0.0.0
    ports:
      - "3000:3000"
      - "1234:1234"
    environment:
      RUBYLIB: ""

  sidekiq:
    <<: *app
    command: bundle exec sidekiq

  clock:
    <<: *app
    command: bundle exec clockwork config/clock.rb

  scrub:
    <<: *app
    command: bin/scrub

  musicbrainz:
    <<: *app
    command: bin/forward
    ports:
      - "5433:5432"
    volumes:
      - .:/app/:cached
      - $HOME/.ssh/:/app/.ssh/:ro
      - $SSH_AUTH_SOCK:/ssh

volumes:
  postgres:
  redis:
  nginx:
  bundle:
