version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: daily
      time: "05:00"
    open-pull-requests-limit: 10
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
    open-pull-requests-limit: 10
