version: "3.8"

services:
  headbanger_app:
    image: ghcr.io/floriandejonckheere/headbanger-app:v0.6.0
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1g"
        compress: "true"
    env_file:
      - .env.production
    restart: unless-stopped

  headbanger_web:
    image: ghcr.io/floriandejonckheere/headbanger-web:v0.6.0
    volumes:
      - ./client.pem:/etc/nginx/conf.d/client.pem
      - ./client.key:/etc/nginx/conf.d/client.key
    depends_on:
      - headbanger_app
    env_file:
      - .env.production
    restart: unless-stopped

  sidekiq:
    image: ghcr.io/floriandejonckheere/headbanger-app:v0.6.0
    command: bundle exec sidekiq
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1g"
        compress: "true"
    env_file:
      - .env.production
    restart: unless-stopped

  clock:
    image: ghcr.io/floriandejonckheere/headbanger-app:v0.6.0
    command: bundle exec clockwork config/clock.rb
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1g"
        compress: "true"
    env_file:
      - .env.production
    restart: unless-stopped

  scrub:
    image: ghcr.io/floriandejonckheere/headbanger-app:v0.6.0
    command: bin/scrub
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1g"
        compress: "true"
    env_file:
      - .env.production
    restart: unless-stopped

networks:
  default:
    external:
      name: thalarion_default
