name: Deploy application

on:
  push:
    paths:
      - 'ops/**'

jobs:
  app:
    name: Deploy application
    # Github Actions ignores paths filters on tag push, so we need to explicitly skip when a tag is pushed
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') && !startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: ops/docker-compose.yml
          target: $HOME
          strip_components: 1

      - name: Deploy application
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          envs: "GITHUB_USER,GITHUB_TOKEN"
          script: |
            echo "Pulling latest images"
            docker login https://docker.pkg.github.com -u ${GITHUB_USER} -p ${GITHUB_TOKEN}
            docker-compose pull --quiet
            echo "Running migrations"
            docker-compose run --rm app rails db:migrate
            echo "Recreating containers"
            docker-compose up -d
