name: Automerge Dependabot PRs

on:
  pull_request:

jobs:
  automerge:
    name: Automerge Dependabot PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Wait for required checks (app)
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          check-name: Continuous Integration (app)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Wait for required checks (web)
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          check-name: Continuous Integration (web)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Merge pull request
        uses: actions/github-script@v3.1
        with:
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'rebase'
            })
          github-token: ${{github.token}}
